MODEL:
  TYPE: anynet
  NUM_CLASSES: 1000
ANYNET:
  STEM_TYPE: res_stem_in
  STEM_W: 64
  BLOCK_TYPE: res_bottleneck_block
  STRIDES: [1, 2, 2, 2]
  DEPTHS: [3, 8, 36, 3]
  WIDTHS: [256, 512, 1024, 2048]
  BOT_MULS: [0.5, 0.5, 0.5, 0.5]
  GROUP_WS: [4, 8, 16, 32]
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.4
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
TRAIN:
  DATASET: imagenet
  IM_SIZE: 224
  BATCH_SIZE: 512
  INTRA_IMGS: 1
  SYNC_BN: True
  USE_BAKE: True
  OMEGA: 0.5
  TEMP: 4.0
  LAMBDA: 1.0
  GLOBAL_KE: True
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 400
