MODEL:
  TYPE: mobilenetv2
  NUM_CLASSES: 1000
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.05
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 4e-5
TRAIN:
  DATASET: imagenet
  IM_SIZE: 224
  BATCH_SIZE: 256
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 200
