MODEL:
  TYPE: resnest
  NUM_CLASSES: 1000
RESNEST:
  STEM_W: 64
  DEPTHS: [3, 4, 23, 3]
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.4
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
TRAIN:
  DATASET: imagenet
  IM_SIZE: 224
  BATCH_SIZE: 512
  INTRA_IMGS: 1
  SYNC_BN: True
  USE_BAKE: True
  OMEGA: 0.5
  TEMP: 4.0
  LAMBDA: 1.0
  GLOBAL_KE: True
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 400
